Document: libvpu-imx6
Title: Debian libvpu-imx6 Manual
Author: <insert document author here>
Abstract: This manual describes what libvpu-imx6 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libvpu-imx6/libvpu-imx6.sgml.gz

Format: postscript
Files: /usr/share/doc/libvpu-imx6/libvpu-imx6.ps.gz

Format: text
Files: /usr/share/doc/libvpu-imx6/libvpu-imx6.text.gz

Format: HTML
Index: /usr/share/doc/libvpu-imx6/html/index.html
Files: /usr/share/doc/libvpu-imx6/html/*.html
